### ISSUE TITLE
bro hello. question mod.

### ISSUE THREAD

**Issue by kitovoi111** [min2222/Cataclysmic-Illagers#1]
I am writing here quietly so that no one can see. can you help me fix alex's caves crash please?

I just don’t have the source code, I don’t even know what to fix..
[crash-2024-03-29_23.47.50-client (3).txt](https://github.com/min2222/Cataclysmic-Illagers/files/15273722/crash-2024-03-29_23.47.50-client.3.txt)

**Comment by kitovoi111** [comment]
AmberMonolithBlockRenderer

**Comment by kitovoi111** [comment]
When I put swamp in the biome it cannot display the platefish mob from the environemntal mod

**Comment by min2222** [comment]
please stop. i'm tired
