### ISSUE TITLE
latest version still tentacles doesn't spawn

### ISSUE THREAD

**Issue by GauntAndreX8** [min2222/Cataclysmic-Illagers#6]
what title says

**Comment by min2222** [comment]
tentacle will be despawn if flying tidal claw is dead or enemy of claw is dead.
do you have any screenshot?

**Comment by GauntAndreX8** [comment]
![2024-05-15_17 06 20](https://github.com/min2222/Cataclysmic-Illagers/assets/85809443/7662df02-a4fc-4d0f-926b-726e89117a08)
sorry for delay, here is the screenshot
